audit_header: false
title: Las Vegas Real Estate Video Blog with Dan Mumm
description: Our mission at Berkshire Hathaway HomeServices is to be your best resource for Las Vegas real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Berkshire Hathaway HomeServices, your professional Las Vegas Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Dan Mumm
  title:
  license_number:
  about_markdown: |
    1. I ANSWER MY PHONE! All calls, texts, and emails returned in 2 business hours (MAX), 1/week PROGRESS REPORT by phone.

    2. Your home sold, GUARANTEED. I put my money where my mouth is. If you are not 100% satisfied, I will give you back my commission. No questions asked.

    3. NO BINDING CONTRACTS. Most brokers are not willing to do whatever it takes to sell a listing quickly, so they lock you into a 6-month or 1-year contract.  I allow my clients to cancel my listings anytime because I know that I ALWAYS overdeliver! (By the way - I have never been fired from a listing!)

    4. I SHOW my own listings. Ever hear the saying, "give the best job to the busiest man?". As a full-time professional closing more deals than 99% of agents, I do whatever it takes to match up my buyers and sellers. I don't rely on other brokers by throwing your home on the MLS and waiting.

    5. YOUR INTERESTS FIRST. ALWAYS. The problem with hiring a low-producing agent? They'll tell you whatever you want to hear out of desperation! As a top-producing agent, I have plenty of business and can be completely honest with you. If I don't think I can help you, or if moving forward on a deal isn't in your best interest, I'LL TELL YOU.
  brand: Berkshire Hathaway HomeServices
  brokerage:
  market: Las Vegas
  address: '3185 St Rose Pkwy #100, Henderson, NV 89052'
  phone: 702-758-6390
  phone_type:
  phone2:
  phone2_type:
  email: danmumm@gmail.com
  url: https://danmumm.bhhsnv.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://bhhsnv.findbuyers.com/Danmumm
  second_CTA_text: Home Search
  second_CTA_URL: https://danmumm.bhhsnv.com/bagr/index.asp?p=findahome.asp&mode=N

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Las Vegas Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://bhhsnv.findbuyers.com/Danmumm

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Las Vegas Home?"
    CTA_text2: "Search the entire MLS for your Las Vegas home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://danmumm.bhhsnv.com/bagr/index.asp?p=findahome.asp&mode=N

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/DanMummPublic/
  linkedin_url: https://www.linkedin.com/in/daniel-mumm-14966836
  youtube_url: https://www.youtube.com/watch?v=oO-D42_rioQ
  twitter_url: 
  instagram_url: https://www.instagram.com/danmumm/
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/dan-mumm/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Las Vegas Real Estate Podcast with Dan Mumm'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Las Vegas Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Berkshire Hathaway HomeServices - your professional Las Vegas Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Las Vegas, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Dan Mumm'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Las Vegas Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#52154d'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#52154d'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
